import type { CatalogProduct } from "./productCatalogTypes";

export const DEFAULT_PINNED_PRODUCT_ID = "glasses-a";

export const DEMO_PRODUCTS: CatalogProduct[] = [
  {
    id: "glasses-a",
    name: "Kính thời trang A",
    category: "glasses",
    description: "Gọng nhẹ, hợp livestream và đi chơi hằng ngày.",
    price: 299_000,
    stock: 25,
    colors: ["Đen", "Vàng"],
    sizes: [],
    imageUrl: "/products/images/glasses-a.svg",
    productUrl: "/products/glasses-a",
    arEffectType: "glasses",
    tags: ["kính", "kinh", "glasses", "thoi trang a", "mat kinh"],
    sellingPoints: ["Gọng nhẹ", "Hợp livestream", "Thử AR trực tiếp"],
  },
  {
    id: "glasses-urban",
    name: "Kính chống nắng Urban",
    category: "glasses",
    description: "Kính râm chống UV, form urban unisex.",
    price: 349_000,
    stock: 18,
    colors: ["Đen", "Xám"],
    sizes: [],
    imageUrl: "/products/images/glasses-urban.svg",
    productUrl: "/products/glasses-urban",
    arEffectType: "glasses",
    tags: ["kính urban", "kinh chong nang", "urban", "ram"],
    sellingPoints: ["Chống UV", "Form urban", "Đi nắng thoải mái"],
  },
  {
    id: "lipstick-ruby",
    name: "Son Ruby Đỏ",
    category: "lipstick",
    description: "Son lì tone ruby đỏ, giữ màu lâu trên livestream.",
    price: 189_000,
    stock: 40,
    colors: ["Ruby Đỏ"],
    sizes: [],
    imageUrl: "/products/images/lipstick-ruby.svg",
    productUrl: "/products/lipstick-ruby",
    arEffectType: "lipstick",
    tags: ["son ruby", "son do", "lipstick", "ruby"],
    sellingPoints: ["Lì", "Tone đỏ nổi", "Thử makeup AR"],
  },
  {
    id: "lipstick-coral",
    name: "Son Cam Đất",
    category: "lipstick",
    description: "Son cam đất everyday, dễ mix với tone da Việt.",
    price: 179_000,
    stock: 32,
    colors: ["Cam Đất"],
    sizes: [],
    imageUrl: "/products/images/lipstick-coral.svg",
    productUrl: "/products/lipstick-coral",
    arEffectType: "lipstick",
    tags: ["son cam", "cam dat", "son moi"],
    sellingPoints: ["Everyday", "Dễ dùng", "Thử makeup AR"],
  },
  {
    id: "crown-accessory",
    name: "Vương miện Phụ kiện tóc",
    category: "accessory",
    description: "Phụ kiện vương miện cho trend livestream vui nhộn.",
    price: 129_000,
    stock: 15,
    colors: ["Vàng", "Bạc"],
    sizes: [],
    imageUrl: "/products/images/crown-accessory.svg",
    productUrl: "/products/crown-accessory",
    arEffectType: "crown",
    tags: ["vuong mien", "crown", "phu kien toc", "vương miện"],
    sellingPoints: ["Trend livestream", "Nổi bật trên cam", "Full filter AR"],
  },
  {
    id: "bucket-hat",
    name: "Mũ bucket",
    category: "accessory",
    description: "Mũ bucket basic, phối streetwear.",
    price: 159_000,
    stock: 20,
    colors: ["Be", "Đen"],
    sizes: ["Free size"],
    imageUrl: "/products/images/bucket-hat.svg",
    productUrl: "/products/bucket-hat",
    arEffectType: "none",
    tags: ["mu bucket", "mũ", "bucket hat"],
    sellingPoints: ["Streetwear", "Free size", "Đi chơi"],
  },
  {
    id: "headphones-mini",
    name: "Tai nghe Bluetooth Mini",
    category: "electronics",
    description: "Tai nghe true wireless nhỏ gọn, pin 4 giờ.",
    price: 459_000,
    stock: 12,
    colors: ["Trắng", "Đen"],
    sizes: [],
    imageUrl: "/products/images/headphones-mini.svg",
    productUrl: "/products/headphones-mini",
    arEffectType: "none",
    tags: ["tai nghe", "bluetooth", "headphones", "true wireless"],
    sellingPoints: ["Nhỏ gọn", "Pin 4h", "Livestream nghe rõ"],
  },
  {
    id: "sunscreen-spf50",
    name: "Kem chống nắng SPF50",
    category: "skincare",
    description: "Kem chống nắng SPF50, finish nhẹ trên livestream.",
    price: 239_000,
    stock: 30,
    colors: [],
    sizes: ["50ml"],
    imageUrl: "/products/images/sunscreen-spf50.svg",
    productUrl: "/products/sunscreen-spf50",
    arEffectType: "none",
    tags: ["kem chong nang", "spf50", "skincare", "chong nang"],
    sellingPoints: ["SPF50", "Finish nhẹ", "Hợp da nhạy cảm"],
  },
  {
    id: "crossbody-basic",
    name: "Túi đeo chéo Basic",
    category: "fashion",
    description: "Túi đeo chéo basic, đựng phone và phụ kiện livestream.",
    price: 219_000,
    stock: 22,
    colors: ["Đen", "Nâu"],
    sizes: [],
    imageUrl: "/products/images/crossbody-basic.svg",
    productUrl: "/products/crossbody-basic",
    arEffectType: "none",
    tags: ["tui deo cheo", "túi", "crossbody", "basic"],
    sellingPoints: ["Basic", "Đựng phone", "Đi live tiện"],
  },
  {
    id: "oversize-tee",
    name: "Áo thun Oversize",
    category: "fashion",
    description: "Áo thun oversize cotton, form unisex.",
    price: 199_000,
    stock: 35,
    colors: ["Trắng", "Đen"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/products/images/oversize-tee.svg",
    productUrl: "/products/oversize-tee",
    arEffectType: "none",
    tags: ["ao thun", "oversize", "thun", "size"],
    sellingPoints: ["Cotton", "Unisex", "Nhiều size"],
  },
];
